name:                projeto-haskell
version:             0.1.0.0
github:              "githubuser/projeto-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/projeto-haskell#readme>

dependencies:
- base
- yesod
- text
- persistent
- persistent-postgresql
- postgresql-simple
- monad-logger
- aeson
- ghc
- bytestring
- optparse-applicative
- yaml
- QuickCheck

default-extensions:
- OverloadedStrings
- QuasiQuotes
- TemplateHaskell
- TypeFamilies
- GADTs
- DerivingStrategies
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- UndecidableInstances
- DataKinds
- FlexibleInstances
- MultiParamTypeClasses
- RecordWildCards

library:
  source-dirs: src

executables:
  projeto-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - projeto-haskell

tests:
  projeto-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - projeto-haskell
